import os
# Chave da API do Google Maps
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Permite ativar/desativar a população automática de imagens reais nos pets
POPULATE_PETS_WITH_IMAGES = True
"""
Django settings for harmony_pets project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
import os
from dotenv import load_dotenv
import sys
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Diretório de logs de aplicação
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)



# Configurações de e-mail para redefinição de senha (usando variáveis de ambiente)
import os

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 465))  # Porta 465 (SSL) ao invés de 587 (TLS)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False") == "True"  # Desabilitado para SSL
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "True") == "True"   # SSL habilitado
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# Remover espaços da senha de app do Gmail
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").replace(" ", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
EMAIL_TIMEOUT = 30  # Timeout de 30 segundos para envio

# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Reduzir logging em produção para economizar recursos
LOG_LEVEL = 'WARNING' if not DEBUG else 'INFO'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
if DEBUG:
    # Permitir hosts comuns em desenvolvimento e testes internos
    ALLOWED_HOSTS.extend(['127.0.0.1','localhost','testserver'])
else:
    # Em produção, adicionar domínio do Render se não especificado
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['.onrender.com']


# Application definition

INSTALLED_APPS = [
    # IMPORTANTE: Apps customizados devem vir ANTES dos apps do Django
    # Isso garante que templates personalizados (ex: registration/*) tenham prioridade
    # sobre templates padrão do django.contrib.admin e django.contrib.auth
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise para servir estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AdminAccessRedirectMiddleware',
    'core.middleware.TermsAcceptanceMiddleware',
    'core.middleware.TwoFactorMiddleware',
    'core.middleware.AuditLogMiddleware',
]

ROOT_URLCONF = 'harmony_pets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
            # Torna disponíveis globalmente os filtros customizados de formatação
            'builtins': [
                'core.templatetags.formatters',
            ],
        },
    },
]

WSGI_APPLICATION = 'harmony_pets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'test' in sys.argv:
    # Durante testes: usar SQLite isolado
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db_test.sqlite3'),
        }
    }
elif os.environ.get('DATABASE_URL'):
    # Produção (Render) - usa DATABASE_URL do ambiente
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=60,  # Reutiliza conexões por 60s (economiza recursos)
            conn_health_checks=True,
            ssl_require=True,
        )
    }
    # Configurações otimizadas para reduzir consumo de recursos
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': 10,
        'options': '-c statement_timeout=15000 -c idle_in_transaction_session_timeout=10000',
    })
    
    # Configurações para Supabase Connection Pooler (pgBouncer)
    if os.environ.get('PGBOUNCER_PREPARED_STATEMENTS') == 'False':
        DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    # Desenvolvimento local - usa variáveis separadas
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'require'),
                'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '5')),
                'keepalives': 1,
                'keepalives_idle': int(os.environ.get('DB_KEEPALIVES_IDLE', '20')),
                'keepalives_interval': int(os.environ.get('DB_KEEPALIVES_INTERVAL', '10')),
                'keepalives_count': int(os.environ.get('DB_KEEPALIVES_COUNT', '3')),
            },
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Idiomas suportados
LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
    ('en', 'English'),
]

# Expiração do link de redefinição de senha (em segundos)
PASSWORD_RESET_TIMEOUT = 3600  # 1 hora



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

# Whitenoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploads de imagens de pets)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração de logging para arquivo rotativo acessível pelo admin
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'app_file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 1024*1024*2,  # 2MB (reduzido de 5MB)
            'backupCount': 2,  # Reduzido de 3 para 2
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['app_file'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
        'core': {
            'handlers': ['app_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Política de exclusão de conta (tornar opcional via ambiente)
# Quando False, a exclusão de conta é desativada para os usuários finais.
ACCOUNT_DELETION_ENABLED = os.environ.get('ACCOUNT_DELETION_ENABLED', 'True') == 'True'

# Configuração de Cache para otimizar performance e reduzir carga no banco
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'harmony-pets-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 500,  # Limitar entrada de cache
        }
    }
}

# Timeout padrão do cache (5 minutos)
CACHE_TIMEOUT = 300

# Configurações de sessão otimizadas
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  # Usa cache + DB
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 1 dia (reduzido)
SESSION_SAVE_EVERY_REQUEST = False  # Só salva quando modificada

# Otimizações adicionais de performance
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB (reduzido de 2.5MB padrão)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DEFAULT_CHARSET = 'utf-8'

# Otimizar geração de URLs
PREPEND_WWW = False
APPEND_SLASH = True

# Desabilitar recursos desnecessários em produção
if not DEBUG:
    # Desabilitar debug toolbar e features de debug
    TEMPLATE_DEBUG = False
    
    # Otimizar static files
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Timeout de request menor
    CONN_MAX_AGE = 60  # Manter conexões por no máximo 60 segundos
