# Generated by Django 5.2.5 on 2025-08-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('coelho', 'Coelho'), ('passaro', 'Pássaro'), ('hamster', 'Hamster'), ('outro', 'Outro')], max_length=20)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('idade', models.PositiveIntegerField(help_text='Idade em meses')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10)),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True)),
                ('castrado', models.BooleanField(default=False)),
                ('vacinado', models.BooleanField(default=False)),
                ('vermifugado', models.BooleanField(default=False)),
                ('docil', models.BooleanField(default=True)),
                ('brincalhao', models.BooleanField(default=False)),
                ('calmo', models.BooleanField(default=False)),
                ('descricao', models.TextField(help_text='Descrição detalhada do pet')),
                ('cuidados_especiais', models.TextField(blank=True, help_text='Cuidados médicos ou especiais necessários')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('adotado', 'Adotado'), ('reservado', 'Reservado')], default='disponivel', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_adocao', models.DateTimeField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, help_text='URL da foto do pet')),
                ('emoji', models.CharField(default='🐕', help_text='Emoji representativo do pet', max_length=10)),
                ('adotado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_adotados', to='core.interessadoadocao')),
                ('local_adocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.localadocao')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Por que você quer adotar este pet?')),
                ('experiencia_pets', models.TextField(help_text='Conte sobre sua experiência com pets')),
                ('situacao_moradia', models.TextField(help_text='Descreva sua situação de moradia (casa, apartamento, quintal, etc.)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('resposta_local', models.TextField(blank=True, help_text='Resposta do local de adoção')),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.interessadoadocao')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.pet')),
            ],
            options={
                'verbose_name': 'Solicitação de Adoção',
                'verbose_name_plural': 'Solicitações de Adoção',
                'ordering': ['-data_solicitacao'],
                'unique_together': {('pet', 'interessado')},
            },
        ),
    ]
