# Generated by Django 5.2.5 on 2025-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet_solicitacaoadocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='interessadoadocao',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude para localização no mapa', null=True),
        ),
        migrations.AddField(
            model_name='interessadoadocao',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude para localização no mapa', null=True),
        ),
        migrations.AddField(
            model_name='localadocao',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude para localização no mapa', null=True),
        ),
        migrations.AddField(
            model_name='localadocao',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude para localização no mapa', null=True),
        ),
    ]
