# Generated by Django 5.2.5 on 2025-08-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interessadoadocao_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Chave secreta para TOTP', max_length=32)),
                ('is_enabled', models.BooleanField(default=False, help_text='Se o 2FA está ativo')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Códigos de backup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autenticação de 2 Fatores',
                'verbose_name_plural': 'Autenticações de 2 Fatores',
            },
        ),
    ]
