# Generated by Django 5.2.5 on 2025-08-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_twofactorauth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AceitacaoTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termos_aceitos', models.BooleanField(default=False, help_text='Se o usuário aceitou os termos de uso')),
                ('lgpd_aceito', models.BooleanField(default=False, help_text='Se o usuário aceitou os termos da LGPD')),
                ('data_aceitacao', models.DateTimeField(auto_now_add=True)),
                ('ip_aceitacao', models.GenericIPAddressField(help_text='IP do usuário no momento da aceitação')),
                ('user_agent', models.TextField(help_text='User Agent do navegador no momento da aceitação')),
                ('versao_termos', models.CharField(default='1.0', help_text='Versão dos termos aceitos', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceitacao_termos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceitação de Termos',
                'verbose_name_plural': 'Aceitações de Termos',
            },
        ),
    ]
