# Generated by Django 5.2.5 on 2025-08-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aceitacaotermos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do pet (upload)', null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL da foto do pet (opcional)'),
        ),
    ]
