# Generated by Django 5.2.5 on 2025-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pet_foto_alter_pet_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude do pet (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude do pet (opcional)', null=True),
        ),
    ]
