# Generated by Django 5.2.5 on 2025-09-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userloginprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginprofile',
            options={'verbose_name': 'Perfil de Login do Usuário', 'verbose_name_plural': 'Perfis de Login de Usuário'},
        ),
        migrations.RemoveField(
            model_name='userloginprofile',
            name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='userloginprofile',
            name='failed_attempts',
        ),
        migrations.AddField(
            model_name='userloginprofile',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, help_text='Usuário bloqueado até este horário', null=True),
        ),
        migrations.AddField(
            model_name='userloginprofile',
            name='tentativas_falhas',
            field=models.PositiveIntegerField(default=0, help_text='Tentativas de login falhas'),
        ),
    ]
