# Generated by Django 5.2.5 on 2025-11-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='preferred_method',
            field=models.CharField(choices=[('totp', 'Autenticador'), ('email', 'E-mail')], default='totp', help_text='Método preferido para segunda etapa (aplicativo ou e-mail)', max_length=10),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='require_every_login',
            field=models.BooleanField(default=True, help_text='Se verdadeiro, a verificação 2FA é exigida em todo novo login'),
        ),
    ]
