# Generated by Django 5.2.5 on 2025-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_twofactorauth_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chamado de Contato',
                'verbose_name_plural': 'Chamados de Contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
