# Generated by Django 5.2.5 on 2025-11-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTicket',
        ),
    ]
