# Generated by Django 5.2.5 on 2025-12-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_delete_contactticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="data_entrevista",
            field=models.DateTimeField(
                blank=True, help_text="Data e hora da entrevista", null=True
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="data_retirada",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora agendada para retirar o pet",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="local_entrevista",
            field=models.TextField(
                blank=True, help_text="Local ou link da entrevista (presencial/online)"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="observacoes_entrevista",
            field=models.TextField(
                blank=True, help_text="Observações sobre a entrevista"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="observacoes_retirada",
            field=models.TextField(
                blank=True, help_text="Observações sobre a retirada do pet"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoadocao",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_entrevista", "Em Entrevista"),
                    ("entrevista_aprovada", "Entrevista Aprovada"),
                    ("entrevista_rejeitada", "Entrevista Rejeitada"),
                    ("agendado", "Agendado para Retirada"),
                    ("concluida", "Adoção Concluída"),
                    ("rejeitada", "Rejeitada"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendente",
                max_length=30,
            ),
        ),
    ]
