# Generated by Django 5.2.5 on 2025-12-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_solicitacaoadocao_data_entrevista_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="data_aceite_termo",
            field=models.DateTimeField(
                blank=True, help_text="Data e hora do aceite do termo", null=True
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="termo_aceito",
            field=models.BooleanField(
                default=False,
                help_text="Se o interessado aceitou o termo de responsabilidade",
            ),
        ),
    ]
