# Generated by Django 5.2.5 on 2025-12-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_solicitacaoadocao_data_aceite_termo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="data_cancelamento",
            field=models.DateTimeField(
                blank=True, help_text="Data e hora do cancelamento", null=True
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoadocao",
            name="justificativa_cancelamento",
            field=models.TextField(
                blank=True,
                help_text="Justificativa do interessado para cancelar a solicitação",
            ),
        ),
    ]
