# Generated by Django 5.2.5 on 2025-12-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_solicitacaoadocao_data_cancelamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Se False, o pet está oculto mas mantém os dados e vínculos",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="data_exclusao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o pet foi ocultado/excluído",
                null=True,
            ),
        ),
    ]
